### ISSUE TITLE
Calendar UI

### ISSUE THREAD

**Issue by pulimoodan** [zshlabs/datewise#10]
Looks like the app needs a lot of works to be done. Is there anyone working on the main calendar UI? May be I can work on that.

**Comment by anuragts** [comment]
No one is currently working on calendar UI, I'll be working on server actions and db stuff.
So feel free to contribute @pulimoodan  , remember the design is in the home route of repo aka ui.jpeg

**Comment by pulimoodan** [comment]
Ok, I saw that and pretty impressed by the design. Will try to implement it perfectly.

**Comment by anuragts** [comment]
Lfg , go for it.

**Comment by anuragts** [comment]
Requested for some changes @pulimoodan

**Comment by pulimoodan** [comment]
Hi there, 
I have added title and time props to the event card. The other possible props are users, icon (I think we need to have some category for events to implement this) and location (there is a map background for some event cards in the ui.jpeg). Hope we can do that later.

**Comment by pulimoodan** [comment]
@anuragts 
There are some issues with the tailwind class names - it won't support dynamic class names, meaning it imports only necessary styles while compiling. 
So, I had to add some dummy code to import all colours we need in the event cards.
Maybe there is a better way.

**Comment by anuragts** [comment]
@pulimoodan I have merged the PR, great work.
