### ISSUE TITLE
Use tRPC (or better yet the T3 stack)

### ISSUE THREAD

**Issue by stylessh** [zshlabs/datewise#5]
I believe we could use [T3 Stack](https://create.t3.gg/) to have a better data fetching and mutations workflow. And also it comes with a better - and configured toolset  out of the box.

**Comment by anuragts** [comment]
I'm not inclined to use T3, or tRPC generally as it would make the project complex, we will be using only react server actions for a MVP
Maybe Migrate in future .
Also will add zod for env validation.
